services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cioos-metadata-conversion-api
    env_file:
      - .env
    environment:
      - API_PORT=${API_PORT:-8000}
    ports:
      - ${API_PORT}:8000
